### ISSUE TITLE
Is it possible to use this work for single image reconstruction?

### ISSUE THREAD

**Issue by YuDeng** [filby89/spectre#11]
Hi, nice work!

I was desired to use this work for single image reconstruction but found that the provided model is designed for video sequences.  
I wonder if it is possible for single image case? For example, if I concatenate a single frame multiple times and send the sequence into the model, does it produce reasonable results?

I also wonder the 3D reconstruction accuracy of this work compare to EMOCA. The original paper did not report this kind of metrics.

Thanks in advance!

**Comment by filby89** [comment]
Hey ! 
I have not really tested in single images since our goal was to leverage temporal dynamics. However, I believe that if you concatenate a frame to build a sequence of 5 it will probably have a good result. Let me know if you try it!

If I'm not mistaken EMOCA did not report reconstruction metrics as well, you must mean DECA. We are currently working in an update of the paper with metrics on reconstruction as well, I will let you know when it is available :)
