### ISSUE TITLE
Magnitude of expression loss while training

### ISSUE THREAD

**Issue by Bowenwu1** [filby89/spectre#14]
Hi, thanks for your wonderful work!
Recently, we're trying to train Spectre on our own dataset, but we find `expression loss` is hard to converge. In order to position problem, we also tried to use official Spectre training setting, also find `expression loss` hard to converge.

So I wonder the magnitude of expression loss before training and after training. And, could you give use some advice to position this problem.

Thanks!

![截屏2023-06-06 10 22 33](https://github.com/filby89/spectre/assets/16816766/14dc5b60-7b35-4450-b479-afa42ba2b3e3)

**Comment by filby89** [comment]
Hey, thanks for your interest in our work. I selected the regularization parameters so that the expression_reg converges at about a value of 40 

![image](https://github.com/filby89/spectre/assets/9838129/a443068a-47c3-448b-b45c-746c61f93b04)
![image](https://github.com/filby89/spectre/assets/9838129/b95fe133-d457-4b7f-9126-93ede26d2f80)

I suggest that you play around a bit with the weight - in my experience it was a good value so that we have expressiveness while constraining the model enough to not introduce artifacts.
