### ISSUE TITLE
dataset  link invalid

### ISSUE THREAD

**Issue by NewtOliver** [filby89/spectre#19]
Thank you for your excellent work! The link to the LRS3 official website dataset is no longer valid. Could you provide a link to your own dataset?

**Comment by ZhangLei999** [comment]
+1

**Comment by filby89** [comment]
Hey,
unfortunately we had downloaded the dataset from the link you have provided. If the dataset is not available then I would suggest maybe using another database. 

A good alternative would be LRS2  since you can download ready extracted landmarks for it from https://github.com/mpc001/Visual_Speech_Recognition_for_Multiple_Languages
