### ISSUE TITLE
How to change training datasets? 

### ISSUE THREAD

**Issue by fcyx** [filby89/spectre#7]
Hi, author, I am wondering how to replace a dataset without landmarks: 1) At present, your code is trained based on the LR3 dataset, and the LR3 has the groudtruth of landmarks. 2) If I replace the dataset, can I delete some landmarks constraints? 3) Are there any special requirements, such as video length size? If I can, I want to  create my own datasets through cameras.

Best,
YangXin

**Comment by filby89** [comment]
Hey,

> 2) If I replace the dataset, can I delete some landmarks constraints?

you can completely remove landmark constraints and try to train on videos with just the lip read and expression loss. In our experience, we did need some landmark constraints because in some cases the outcome would include artifacts in either the eyes or the mouth (See Figure 4 in https://arxiv.org/pdf/2207.11094.pdf). However you can probably obtain good results with just using the lip read loss.

> 3) Are there any special requirements, such as video length size? 

There are no contraints for the video size - we trained on chunks of 20 frames due to memory issues in our GPU, however it should work in arbitrary sizes. If the videos you record become too large for your GPU, you can always use our approach and sample random segments of the video during training. 

Let me know of the outcome :)

**Comment by fcyx** [comment]
These are very helpful to me. Thank you!

**Comment by filby89** [comment]
One more note, we do not have any GT landmarks on LRS3 either - we just use a face alignment method  (e.g. https://github.com/1adrianb/face-alignment) and then use the predicted ones for supervision. You could try that as well.
